name: echo_ai_new
description: "AI Tutor - Your Personal Learning Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_tts: ^3.8.5
  google_mlkit_text_recognition: ^0.11.0
  google_mobile_ads: ^3.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true